### PR TITLE
5.2.4 reformatting

### PR DESCRIPTION
**Pull request by timj**
* Reformat to use modern latex style (now looks like a real LSST document).
* Modernize latex and reference appendices as proper sections.
* Add bibliography.
* Update URL to key numbers and also include Docushare link.
* Fix two broken links to important documents and replace them with citations.

No changes to any content. I am hoping this we can do a quick LCR for this. Do not merge this PR until LCR approves.

### CODE REVIEW

**Comment by ivezic** [comment]
No changes to any content, good to merge.

**Review by ivezic — APPROVED** [review]
Most excellent!

**Comment by timj** [comment]
Ok. I'll prepare an LCR.

**Comment by timj** [comment]
It looks like the web site has been fixed such that the URLs work again. I'll probably combine these changes with #2 (changing the ordering so that the text changes are later in the history).

**Pull request merged**
